using UnityEngine;

public class PlayerAttack : MonoBehaviour
{
    [Header("ConfiguraciÃ³n de ataque")]
    public float attackRange = 2f;
    public int attackDamage = 20;
    public float attackCooldown = 0.8f;

    [Header("DetecciÃ³n")]
    public LayerMask enemyLayers;

    private float nextAttackTime = 0f;

    void Update()
    {
        if (Time.time >= nextAttackTime)
        {
            if (Input.GetMouseButtonDown(0))
            {
                Attack();
                nextAttackTime = Time.time + attackCooldown;
            }
        }
    }

    void Attack()
    {
        Debug.Log("Ataque ejecutado ðŸ”ª");

        Collider[] hitEnemies = Physics.OverlapSphere(transform.position, attackRange, enemyLayers);

        foreach (Collider enemy in hitEnemies)
        {
            EnemyHealth eh = enemy.GetComponent<EnemyHealth>();

            if (eh != null)
            {
                eh.TakeDamage(attackDamage);
                Debug.Log($"DaÃ±o aplicado a {enemy.name}: {attackDamage}");
            }
        }
    }

    void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position, attackRange);
    }
}
